server:
  port: 8090

spring:
  application:
    name: workload-service

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: health, info

logging:
  pattern:
    level: "%5p [%X{txId:-no-tx}]"