server:
  port: 8080

spring:
  application:
    name: gym-crm-prod
  profiles:
    active: default

  datasource:
    username: sa
    password: s3cr3t
    url: jdbc:postgresql://localhost:5432/gymcrm
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

  sql:
    init:
      mode: always
      data-locations: classpath:data.sql

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

security:
  bruteforce:
    max-attempts: 3
    block-minutes: 5

  jwt:
    secret: ${JWT_SECRET:'this-is-a-very-long-32+chars-secret-key!!'}
    issuer: gym-crm
    access-token-minutes: 30

  cors:
    allowed-origins: "https://app.gym-crm.com"

logging:
  level:
    root: WARN
    com.epam.gymcrm: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: when_authorized
  prometheus:
    metrics:
      export:
        enabled: true

feign:
  client:
    config:
      default:
        connectTimeout: 2000
        readTimeout: 3000

resilience4j:
  circuitbreaker:
    instances:
      workload:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
  retry:
    instances:
      workload:
        maxAttempts: 3
        waitDuration: 200ms